#!/bin/sh

set -e

if [ -z "$1" ]; then
  echo "missing program name to install"
  exit 1
fi

sudo curl https://raw.githubusercontent.com/lucabrunox/try-without-install/refs/heads/main/bin/$1 -o /usr/local/bin/$1 && sudo chmod +x /usr/local/bin/$1